function myf() {
    var e = new XMLHttpRequest;
    e.open("GET", "https://script.google.com/macros/s/AKfycbxLGIuMepv0KmkjffgkpCRrItgvfTis09tAUc-hAKo0FpStnVD0F4LJrjBjExywTbQ1Dw/exec", !0), e.send(), e.onload = function() {
        var E = JSON.parse(e.responseText),
            _ = document.getElementsByName("EQUIPMENT_ID")[0].value,
            t = document.getElementsByName("MAINTENANCE_TYPE")[0].value;
        "MONTHLY" == t ? (document.getElementsByName("DONE_DATE")[0].value = E[8][_], $("#nextBtn").click(), "CHECKED" == E[0][_].toUpperCase() ? document.getElementsByName("CHECK_AND_NOTE_VOLTAGE_CURRENT_IMBLANCE")[0].checked = !0 : document.getElementsByName("CHECK_AND_NOTE_VOLTAGE_CURRENT_IMBLANCE")[1].checked = !0, "CHECKED" == E[1][_].toUpperCase() ? document.getElementsByName("CHECK_FOR_ABNORMAL_NOISE_VIBRATION_DAMAGE")[0].checked = !0 : document.getElementsByName("CHECK_FOR_ABNORMAL_NOISE_VIBRATION_DAMAGE")[1].checked = !0, "CHECKED" == E[2][_].toUpperCase() ? document.getElementsByName("CLEAN_AIR_FILTER_AND_REPLACE_IF_REQUIRED")[0].checked = !0 : document.getElementsByName("CLEAN_AIR_FILTER_AND_REPLACE_IF_REQUIRED")[1].checked = !0, "CHECKED" == E[3][_].toUpperCase() ? document.getElementsByName("CHECK_LOOSENESS_OF_BOLT_FAN_CASING_MOTOR_BASE")[0].checked = !0 : document.getElementsByName("CHECK_LOOSENESS_OF_BOLT_FAN_CASING_MOTOR_BASE")[1].checked = !0, "CHECKED" == E[4][_].toUpperCase() ? document.getElementsByName("EXAMINE_MOTOR_FAN_CANVAS_ANCILLARY_FITTINGS")[0].checked = !0 : document.getElementsByName("EXAMINE_MOTOR_FAN_CANVAS_ANCILLARY_FITTINGS")[1].checked = !0, "CHECKED" == E[5][_].toUpperCase() ? document.getElementsByName("CHECK_CLEANINESS_OF_FAN_BLADES_AND_PHY_DAMAGE")[0].checked = !0 : document.getElementsByName("CHECK_CLEANINESS_OF_FAN_BLADES_AND_PHY_DAMAGE")[1].checked = !0, document.getElementsByName("REMARKS")[0].value = E[6][_]) : "WEEKLY" == t && (document.getElementsByName("DONE_DATE")[0].value = E[7][_], $("#nextBtn").click(), "CHECKED" == E[0][_].toUpperCase() ? document.getElementsByName("CHECK_AND_NOTE_VOLTAGE_CURRENT_IMBLANCE")[0].checked = !0 : document.getElementsByName("CHECK_AND_NOTE_VOLTAGE_CURRENT_IMBLANCE")[1].checked = !0, "CHECKED" == E[1][_].toUpperCase() ? document.getElementsByName("CHECK_FOR_ABNORMAL_NOISE_VIBRATION_DAMAGE")[0].checked = !0 : document.getElementsByName("CHECK_FOR_ABNORMAL_NOISE_VIBRATION_DAMAGE")[1].checked = !0, "CHECKED" == E[2][_].toUpperCase() ? document.getElementsByName("CLEAN_AIR_FILTER_AND_REPLACE_IF_REQUIRED")[0].checked = !0 : document.getElementsByName("CLEAN_AIR_FILTER_AND_REPLACE_IF_REQUIRED")[1].checked = !0, document.getElementsByName("REMARKS")[0].value = E[6][_])
    }
}
myf();
